/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Editor: typeof import('primevue/editor')['default']
    Form: typeof import('@primevue/forms/form')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleButton: typeof import('./src/components/SimpleButton/SimpleButton.vue')['default']
    SimpleInput: typeof import('./src/components/SimpleInput/SimpleInput.vue')['default']
    SimpleTile: typeof import('./src/components/SimpleTile/SimpleTile.vue')['default']
  }
}
