version: '3'

services:
    front-end:
        image: nginx:stable
        ports:
            - "80:80"
        volumes:
            - C:/Users/bombe/git/neuronio/apps/client/dist:/usr/share/nginx/html:ro
    
    back-end:
        image: node:22.14.0
        volumes:
            - C:\Users\bombe\git\neuronio\apps\client:/app
        environment:
            - DATABASE_HOST=database
            - DATABASE_USER=neuronio
            - DATABASE_PASSWORD=0wFN3Xt29kVE
            - DATABASE_NAME=neuronio
        working_dir: /app
        command: ["npm", "run", "start:prod"]
        depends_on:
            - database

    database:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=neuronio
            - POSTGRES_USER=neuronio
            - POSTGRES_PASSWORD=0wFN3Xt29kVE
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: